### ISSUE TITLE
Syncing not working

### ISSUE THREAD

**Issue by ch7amada** [adil192/saber#118]
Really love the app. But syncing is not working. I created a nextcloud account und signed in. But when i write notes on my samsung galaxy s6 lite, it does not appear on my pc (PopOs).
The syncing arrows in the right up corners keep spinning but nothing happens. I checked in Nextcloud, and there are definitly some files in the saber Folder.

Thanks again for this great app

**Comment by adil192** [comment]
Done some debugging on my end, and just to confirm my suspicions on where the bug is, are you logging in with an email or username?

**Comment by ch7amada** [comment]
With username still not working. The sync arrows only spin and nothing happens.


![Screenshot_20221210-004714](https://user-images.githubusercontent.com/120123524/206813291-7f6638e8-becd-4eb3-a341-6c3e356e7196.png)

**Comment by adil192** [comment]
> With username still not working. The sync arrows only spin and nothing happens.

What about if you restart the app?

**Comment by ch7amada** [comment]
> > With username still not working. The sync arrows only spin and nothing happens.
> 
> What about if you restart the app?

I have:
- restarted
- reinstalled
- logged out und then logged in
Nothing worked

**Comment by adil192** [comment]
@ch7amada Please can you try deleting the Saber folder in [Nextcloud](https://nc.saber.adil.hanney.org)?

**Comment by watson96** [comment]
I have my own NC instance and am not able to login. I mean the Saber folder is getting created in the instance but the logging in animation keeps spinning in the saber app.

**Comment by adil192** [comment]
> the logging in animation keeps spinning in the saber app.

If you mean the button on the login page, this should be fixed in v0.4.6 when it releases

**Comment by ch7amada** [comment]
> @ch7amada Please can you try deleting the Saber folder in [Nextcloud](https://nc.saber.adil.hanney.org), and then logging into the app again?

That worked. Thanks
