### ISSUE TITLE
Not getting signup verification email for Nextcloud.

### ISSUE THREAD

**Issue by icantremember** [adil192/saber#856]
### Describe the bug

New install on Linux (chromebook). Flatpak installed fine, registration link opens default browser but any email address I try results in "A problem occurred sending email, please contact your administrator." and no email ever arrives.

Any ideas?

### To reproduce

Click Sign up now...
enter email address and click Request verification link.

### Expected behavior

verification email would be received

### Saber version

v0.14.11

### Device

- Device: Acer Spin 714
- OS: ChromeOS 116, default linux container

**Comment by adil192** [comment]
I think this should be fixed now, please can you try again?

**Comment by icantremember** [comment]
Just tried on Android and while there's no more error, I still don't get the verification email.

**Comment by BestCoder1877** [comment]
I get same issue now with the exact same error

**Comment by adil192** [comment]
Thanks for reporting the issue. I migrated to a new server which blocked emails by default. Fixed now!
